# services:
  # backend:
    # container_name: meetingfinder-backend
    # build:
      # context: ./backend
    # ports:
      # - "3000:3000"
    # volumes:
      # - ./backend:/app
      # - /app/node_modules
    # environment:
      # - PORT=3000
  # frontend:
    # container_name: meetingfinder-frontend
    # build:
      # context: ./frontend
    # ports:
      # - "5173:5173"
    # volumes:
      # - ./frontend:/app
      # - /app/node_modules
      
version: "3.9"

services:
  backend:
    container_name: meetingfinder-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped

  frontend:
    container_name: meetingfinder-frontend
    build:
      context: ./frontend
    ports:
      - "5173:80"
    restart: unless-stopped